In [1]:
import matplotlib.pyplot as plt

import numpy as np
import time
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
import numpy

import xgboost as xgb
np.set_printoptions(suppress=True)
%matplotlib inline

from sklearn.preprocessing import MinMaxScaler
from pylab import *
mpl.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False 
import seaborn as sns 
sns.set_palette('hls')
import numpy as np
from sklearn import metrics
from sklearn.metrics import mean_squared_error #均方误差
from sklearn.metrics import mean_absolute_error #平方绝对误差
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.models import Sequential, load_model

In [2]:
# 读取BCHAIN-MKPRU.csv文件
df_BM = pd.read_csv('BCHAIN-MKPRU.csv', encoding='utf-8')
# 读取LBMA-GOLD.csv文件
df_GOLD = pd.read_csv('LBMA-GOLD.csv', encoding='utf-8')

df = pd.merge(df_BM, df_GOLD, how='outer', on='Date')

df["Date"] = df["Date"].apply(lambda x: time.strftime('%Y/%m/%d', time.strptime(x, '%m/%d/%y')))

df = df.sort_values("Date")

df.columns=['Date','bitcoin','gold']

df['gold_future']=df['gold'].fillna(method='bfill')
df_origin=df
df_origin

In [4]:

from sklearn.metrics import r2_score

def split_sequences(dataset, look_back):
    dataX, dataY = [], []
    for i in range(len(dataset)-look_back-1):
        a = dataset[i:(i+look_back)]
        dataX.append(a)
        dataY.append(dataset[i + look_back])
    return numpy.array(dataX),numpy.array(dataY)
    
def lstm(dataset,n_steps,path):

    in_seq1= dataset[:,0].reshape((dataset.shape[0], 1))
    X, y = split_sequences(dataset, n_steps)
    model = Sequential()
    model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps, 1)))
    model.add(LSTM(50, activation='relu'))
    model.add(Dense(1))
    model.compile(optimizer='adam', loss='mse')
    model.fit(X, y, epochs=500, verbose=2,shuffle=False)
    model.save(path)
    last_input=np.array(dataset[-1:,:])
    return X,y,last_input,n_steps

In [5]:
dataset = df_BM['Value'].values
# 将整型变为float
dataset = dataset.astype('float32').reshape(-1, 1) 
#对数据集合进行标准化
scaler = MinMaxScaler(feature_range=(0, 1))
dataset=scaler.fit_transform(dataset).astype('float32')
X,y,x_input_last,n_steps=lstm(dataset,1,'BM.h5')

Train on 1824 samples
Epoch 1/500
1824/1824 - 4s - loss: 0.0538
Epoch 2/500
1824/1824 - 0s - loss: 0.0437
Epoch 3/500
1824/1824 - 0s - loss: 0.0419
Epoch 4/500
1824/1824 - 0s - loss: 0.0391
Epoch 5/500
1824/1824 - 0s - loss: 0.0349
Epoch 6/500
1824/1824 - 0s - loss: 0.0293
Epoch 7/500
1824/1824 - 0s - loss: 0.0227
Epoch 8/500
1824/1824 - 0s - loss: 0.0154
Epoch 9/500
1824/1824 - 0s - loss: 0.0087
Epoch 10/500
1824/1824 - 0s - loss: 0.0041
Epoch 11/500
1824/1824 - 0s - loss: 0.0020
Epoch 12/500
1824/1824 - 0s - loss: 0.0013
Epoch 13/500
1824/1824 - 0s - loss: 0.0011
Epoch 14/500
1824/1824 - 0s - loss: 0.0011
Epoch 15/500
1824/1824 - 0s - loss: 0.0011
Epoch 16/500
1824/1824 - 0s - loss: 0.0010
Epoch 17/500
1824/1824 - 0s - loss: 0.0010
Epoch 18/500
1824/1824 - 0s - loss: 9.9762e-04
Epoch 19/500
1824/1824 - 0s - loss: 9.8298e-04
Epoch 20/500
1824/1824 - 0s - loss: 9.6745e-04
Epoch 21/500
1824/1824 - 0s - loss: 9.5135e-04
Epoch 22/500
1824/1824 - 0s - loss: 9.3459e-04
Epoch 23/500
1824/1824 - 0s - loss: 9.1748e-04
Epoch 24/500
1824/1824 - 0s - loss: 8.9983e-04
Epoch 25/500
1824/1824 - 0s - loss: 8.8153e-04
Epoch 26/500
1824/1824 - 0s - loss: 8.6272e-04
Epoch 27/500
1824/1824 - 0s - loss: 8.4375e-04
Epoch 28/500
1824/1824 - 0s - loss: 8.2414e-04
Epoch 29/500
1824/1824 - 0s - loss: 8.0342e-04
Epoch 30/500
1824/1824 - 0s - loss: 7.8218e-04
Epoch 31/500
1824/1824 - 0s - loss: 7.6110e-04
Epoch 32/500
1824/1824 - 0s - loss: 7.3999e-04
Epoch 33/500
1824/1824 - 0s - loss: 7.1756e-04
Epoch 34/500
1824/1824 - 0s - loss: 6.9381e-04
Epoch 35/500
1824/1824 - 0s - loss: 6.7170e-04
Epoch 36/500
1824/1824 - 0s - loss: 6.4808e-04
Epoch 37/500
1824/1824 - 0s - loss: 6.2330e-04
Epoch 38/500
1824/1824 - 0s - loss: 5.9939e-04
Epoch 39/500
1824/1824 - 0s - loss: 5.7654e-04
Epoch 40/500
1824/1824 - 0s - loss: 5.5058e-04
Epoch 41/500
1824/1824 - 0s - loss: 5.2760e-04
Epoch 42/500
1824/1824 - 0s - loss: 5.0305e-04
Epoch 43/500
1824/1824 - 0s - loss: 4.7949e-04
Epoch 44/500
1824/1824 - 0s - loss: 4.5570e-04
Epoch 45/500
1824/1824 - 0s - loss: 4.3246e-04
Epoch 46/500
1824/1824 - 0s - loss: 4.1036e-04
Epoch 47/500
1824/1824 - 0s - loss: 3.8809e-04
Epoch 48/500
1824/1824 - 0s - loss: 3.6759e-04
Epoch 49/500
1824/1824 - 0s - loss: 3.4620e-04
Epoch 50/500
1824/1824 - 0s - loss: 3.2844e-04
Epoch 51/500
1824/1824 - 0s - loss: 3.0892e-04
Epoch 52/500
1824/1824 - 0s - loss: 2.9349e-04
Epoch 53/500
1824/1824 - 0s - loss: 2.7610e-04
Epoch 54/500
1824/1824 - 0s - loss: 2.6345e-04
Epoch 55/500
1824/1824 - 0s - loss: 2.4848e-04
Epoch 56/500
1824/1824 - 0s - loss: 2.3827e-04
Epoch 57/500
1824/1824 - 0s - loss: 2.2610e-04
Epoch 58/500
1824/1824 - 0s - loss: 2.1780e-04
Epoch 59/500
1824/1824 - 0s - loss: 2.0871e-04
Epoch 60/500
1824/1824 - 0s - loss: 2.0200e-04
Epoch 61/500
1824/1824 - 0s - loss: 1.9552e-04
Epoch 62/500
1824/1824 - 0s - loss: 1.9045e-04
Epoch 63/500
1824/1824 - 0s - loss: 1.8589e-04
Epoch 64/500
1824/1824 - 0s - loss: 1.8265e-04
Epoch 65/500
1824/1824 - 0s - loss: 1.7910e-04
Epoch 66/500
1824/1824 - 0s - loss: 1.7662e-04
Epoch 67/500
1824/1824 - 0s - loss: 1.7430e-04
Epoch 68/500
1824/1824 - 0s - loss: 1.7299e-04
Epoch 69/500
1824/1824 - 0s - loss: 1.7235e-04
Epoch 70/500
1824/1824 - 0s - loss: 1.7232e-04
Epoch 71/500
1824/1824 - 0s - loss: 1.7291e-04
Epoch 72/500
1824/1824 - 0s - loss: 1.7396e-04
Epoch 73/500
1824/1824 - 0s - loss: 1.7527e-04
Epoch 74/500
1824/1824 - 0s - loss: 1.7698e-04
Epoch 75/500
1824/1824 - 0s - loss: 1.7918e-04
Epoch 76/500
1824/1824 - 0s - loss: 1.8199e-04
Epoch 77/500
1824/1824 - 0s - loss: 1.8528e-04
Epoch 78/500
1824/1824 - 0s - loss: 1.8907e-04
Epoch 79/500
1824/1824 - 0s - loss: 1.9360e-04
Epoch 80/500
1824/1824 - 0s - loss: 1.9863e-04
Epoch 81/500
1824/1824 - 0s - loss: 2.0397e-04
Epoch 82/500
1824/1824 - 0s - loss: 2.0936e-04
Epoch 83/500
1824/1824 - 0s - loss: 2.1435e-04
Epoch 84/500
1824/1824 - 0s - loss: 2.1856e-04
Epoch 85/500
1824/1824 - 0s - loss: 2.2174e-04
Epoch 86/500
1824/1824 - 0s - loss: 2.2387e-04
Epoch 87/500
1824/1824 - 0s - loss: 2.2507e-04
Epoch 88/500
1824/1824 - 0s - loss: 2.2558e-04
Epoch 89/500
1824/1824 - 0s - loss: 2.2563e-04
Epoch 90/500
1824/1824 - 0s - loss: 2.2547e-04
Epoch 91/500
1824/1824 - 0s - loss: 2.2521e-04
Epoch 92/500
1824/1824 - 0s - loss: 2.2511e-04
Epoch 93/500
1824/1824 - 0s - loss: 2.2505e-04
Epoch 94/500
1824/1824 - 0s - loss: 2.2533e-04
Epoch 95/500
1824/1824 - 0s - loss: 2.2573e-04
Epoch 96/500
1824/1824 - 0s - loss: 2.2631e-04
Epoch 97/500
1824/1824 - 0s - loss: 2.2688e-04
Epoch 98/500
1824/1824 - 0s - loss: 2.2740e-04
Epoch 99/500
1824/1824 - 0s - loss: 2.2789e-04
Epoch 100/500
1824/1824 - 0s - loss: 2.2838e-04
Epoch 101/500
1824/1824 - 0s - loss: 2.2894e-04
Epoch 102/500
1824/1824 - 0s - loss: 2.2955e-04
Epoch 103/500
1824/1824 - 0s - loss: 2.2993e-04
Epoch 104/500
1824/1824 - 0s - loss: 2.2994e-04
Epoch 105/500
1824/1824 - 0s - loss: 2.3012e-04
Epoch 106/500
1824/1824 - 0s - loss: 2.3057e-04
Epoch 107/500
1824/1824 - 0s - loss: 2.3079e-04
Epoch 108/500
1824/1824 - 0s - loss: 2.3118e-04
Epoch 109/500
1824/1824 - 0s - loss: 2.3164e-04
Epoch 110/500
1824/1824 - 0s - loss: 2.3201e-04
Epoch 111/500
1824/1824 - 0s - loss: 2.3240e-04
Epoch 112/500
1824/1824 - 0s - loss: 2.3270e-04
Epoch 113/500
1824/1824 - 0s - loss: 2.3323e-04
Epoch 114/500
1824/1824 - 0s - loss: 2.3379e-04
Epoch 115/500
1824/1824 - 0s - loss: 2.3440e-04
Epoch 116/500
1824/1824 - 0s - loss: 2.3497e-04
Epoch 117/500
1824/1824 - 0s - loss: 2.3543e-04
Epoch 118/500
1824/1824 - 0s - loss: 2.3594e-04
Epoch 119/500
1824/1824 - 0s - loss: 2.3604e-04
Epoch 120/500
1824/1824 - 0s - loss: 2.3630e-04
Epoch 121/500
1824/1824 - 0s - loss: 2.3647e-04
Epoch 122/500
1824/1824 - 0s - loss: 2.3683e-04
Epoch 123/500
1824/1824 - 0s - loss: 2.3760e-04
Epoch 124/500
1824/1824 - 0s - loss: 2.3863e-04
Epoch 125/500
1824/1824 - 0s - loss: 2.3870e-04
Epoch 126/500
1824/1824 - 0s - loss: 2.3812e-04
Epoch 127/500
1824/1824 - 0s - loss: 2.3785e-04
Epoch 128/500
1824/1824 - 0s - loss: 2.3755e-04
Epoch 129/500
1824/1824 - 0s - loss: 2.3785e-04
Epoch 130/500
1824/1824 - 0s - loss: 2.3874e-04
Epoch 131/500
1824/1824 - 0s - loss: 2.3990e-04
Epoch 132/500
1824/1824 - 0s - loss: 2.4070e-04
Epoch 133/500
1824/1824 - 0s - loss: 2.4083e-04
Epoch 134/500
1824/1824 - 0s - loss: 2.4083e-04
Epoch 135/500
1824/1824 - 0s - loss: 2.4083e-04
Epoch 136/500
1824/1824 - 0s - loss: 2.4091e-04
Epoch 137/500
1824/1824 - 0s - loss: 2.4128e-04
Epoch 138/500
1824/1824 - 0s - loss: 2.4205e-04
Epoch 139/500
1824/1824 - 0s - loss: 2.4248e-04
Epoch 140/500
1824/1824 - 0s - loss: 2.4267e-04
Epoch 141/500
1824/1824 - 0s - loss: 2.4293e-04
Epoch 142/500
1824/1824 - 0s - loss: 2.4314e-04
Epoch 143/500
1824/1824 - 0s - loss: 2.4336e-04
Epoch 144/500
1824/1824 - 0s - loss: 2.4371e-04
Epoch 145/500
1824/1824 - 0s - loss: 2.4422e-04
Epoch 146/500
1824/1824 - 0s - loss: 2.4440e-04
Epoch 147/500
1824/1824 - 0s - loss: 2.4422e-04
Epoch 148/500
1824/1824 - 0s - loss: 2.4387e-04
Epoch 149/500
1824/1824 - 0s - loss: 2.4380e-04
Epoch 150/500
1824/1824 - 0s - loss: 2.4402e-04
Epoch 151/500
1824/1824 - 0s - loss: 2.4400e-04
Epoch 152/500
1824/1824 - 0s - loss: 2.4391e-04
Epoch 153/500
1824/1824 - 0s - loss: 2.4384e-04
Epoch 154/500
1824/1824 - 0s - loss: 2.4352e-04
Epoch 155/500
1824/1824 - 0s - loss: 2.4312e-04
Epoch 156/500
1824/1824 - 0s - loss: 2.4291e-04
Epoch 157/500
1824/1824 - 0s - loss: 2.4283e-04
Epoch 158/500
1824/1824 - 0s - loss: 2.4242e-04
Epoch 159/500
1824/1824 - 0s - loss: 2.4180e-04
Epoch 160/500
1824/1824 - 0s - loss: 2.4139e-04
Epoch 161/500
1824/1824 - 0s - loss: 2.4074e-04
Epoch 162/500
1824/1824 - 0s - loss: 2.4077e-04
Epoch 163/500
1824/1824 - 0s - loss: 2.4115e-04
Epoch 164/500
1824/1824 - 0s - loss: 2.4162e-04
Epoch 165/500
1824/1824 - 0s - loss: 2.4166e-04
Epoch 166/500
1824/1824 - 0s - loss: 2.4171e-04
Epoch 167/500
1824/1824 - 0s - loss: 2.4162e-04
Epoch 168/500
1824/1824 - 0s - loss: 2.4165e-04
Epoch 169/500
1824/1824 - 0s - loss: 2.4193e-04
Epoch 170/500
1824/1824 - 0s - loss: 2.4224e-04
Epoch 171/500
1824/1824 - 0s - loss: 2.4234e-04
Epoch 172/500
1824/1824 - 0s - loss: 2.4237e-04
Epoch 173/500
1824/1824 - 0s - loss: 2.4246e-04
Epoch 174/500
1824/1824 - 0s - loss: 2.4244e-04

Epoch 175/500
1824/1824 - 0s - loss: 2.4233e-04
Epoch 176/500
1824/1824 - 0s - loss: 2.4225e-04
Epoch 177/500
1824/1824 - 0s - loss: 2.4260e-04
Epoch 178/500
1824/1824 - 0s - loss: 2.4243e-04
Epoch 179/500
1824/1824 - 0s - loss: 2.4228e-04
Epoch 180/500
1824/1824 - 0s - loss: 2.4237e-04
Epoch 181/500
1824/1824 - 0s - loss: 2.4226e-04
Epoch 182/500
1824/1824 - 0s - loss: 2.4216e-04
Epoch 183/500
1824/1824 - 0s - loss: 2.4214e-04
Epoch 184/500
1824/1824 - 0s - loss: 2.4208e-04
Epoch 185/500
1824/1824 - 0s - loss: 2.4201e-04
Epoch 186/500
1824/1824 - 0s - loss: 2.4205e-04
Epoch 187/500
1824/1824 - 0s - loss: 2.4185e-04
Epoch 188/500
1824/1824 - 0s - loss: 2.4179e-04
Epoch 189/500
1824/1824 - 0s - loss: 2.4189e-04
Epoch 190/500
1824/1824 - 0s - loss: 2.4175e-04
Epoch 191/500
1824/1824 - 0s - loss: 2.4161e-04
Epoch 192/500
1824/1824 - 0s - loss: 2.4166e-04
Epoch 193/500
1824/1824 - 0s - loss: 2.4143e-04
Epoch 194/500
1824/1824 - 0s - loss: 2.4156e-04
Epoch 195/500
1824/1824 - 0s - loss: 2.4151e-04
Epoch 196/500
1824/1824 - 0s - loss: 2.4130e-04
Epoch 197/500
1824/1824 - 0s - loss: 2.4149e-04
Epoch 198/500
1824/1824 - 0s - loss: 2.4149e-04
Epoch 199/500
1824/1824 - 0s - loss: 2.4126e-04
Epoch 200/500
1824/1824 - 0s - loss: 2.4148e-04
Epoch 201/500
1824/1824 - 0s - loss: 2.4149e-04
Epoch 202/500
1824/1824 - 0s - loss: 2.4136e-04
Epoch 203/500
1824/1824 - 0s - loss: 2.4131e-04
Epoch 204/500
1824/1824 - 0s - loss: 2.4139e-04
Epoch 205/500
1824/1824 - 0s - loss: 2.4142e-04
Epoch 206/500
1824/1824 - 0s - loss: 2.4116e-04
Epoch 207/500
1824/1824 - 0s - loss: 2.4127e-04
Epoch 208/500
1824/1824 - 0s - loss: 2.4108e-04
Epoch 209/500
1824/1824 - 0s - loss: 2.4125e-04
Epoch 210/500
1824/1824 - 0s - loss: 2.4122e-04
Epoch 211/500
1824/1824 - 0s - loss: 2.4093e-04
Epoch 212/500
1824/1824 - 0s - loss: 2.4111e-04
Epoch 213/500
1824/1824 - 0s - loss: 2.4130e-04
Epoch 214/500
1824/1824 - 0s - loss: 2.4098e-04
Epoch 215/500
1824/1824 - 0s - loss: 2.4106e-04
Epoch 216/500
1824/1824 - 0s - loss: 2.4099e-04
Epoch 217/500
1824/1824 - 0s - loss: 2.4122e-04
Epoch 218/500
1824/1824 - 0s - loss: 2.4105e-04
Epoch 219/500
1824/1824 - 0s - loss: 2.4112e-04
Epoch 220/500
1824/1824 - 0s - loss: 2.4104e-04
Epoch 221/500
1824/1824 - 0s - loss: 2.4111e-04
Epoch 222/500
1824/1824 - 0s - loss: 2.4111e-04
Epoch 223/500
1824/1824 - 0s - loss: 2.4093e-04
Epoch 224/500
1824/1824 - 0s - loss: 2.4121e-04
Epoch 225/500
1824/1824 - 0s - loss: 2.4099e-04
Epoch 226/500
1824/1824 - 0s - loss: 2.4101e-04
Epoch 227/500
1824/1824 - 0s - loss: 2.4090e-04
Epoch 228/500
1824/1824 - 0s - loss: 2.4097e-04
Epoch 229/500
1824/1824 - 0s - loss: 2.4088e-04
Epoch 230/500
1824/1824 - 0s - loss: 2.4087e-04
Epoch 231/500
1824/1824 - 0s - loss: 2.4090e-04
Epoch 232/500
1824/1824 - 0s - loss: 2.4068e-04
Epoch 233/500
1824/1824 - 0s - loss: 2.4085e-04
Epoch 234/500
1824/1824 - 0s - loss: 2.4065e-04
Epoch 235/500
1824/1824 - 0s - loss: 2.4076e-04
Epoch 236/500
1824/1824 - 0s - loss: 2.4069e-04
Epoch 237/500
1824/1824 - 0s - loss: 2.4051e-04
Epoch 238/500
1824/1824 - 0s - loss: 2.4054e-04
Epoch 239/500
1824/1824 - 0s - loss: 2.4044e-04
Epoch 240/500
1824/1824 - 0s - loss: 2.4053e-04
Epoch 241/500
1824/1824 - 0s - loss: 2.4036e-04
Epoch 242/500
1824/1824 - 0s - loss: 2.4045e-04
Epoch 243/500
1824/1824 - 0s - loss: 2.2742e-04
Epoch 244/500
1824/1824 - 0s - loss: 2.5537e-04
Epoch 245/500
1824/1824 - 0s - loss: 2.5108e-04
Epoch 246/500
1824/1824 - 0s - loss: 2.4499e-04
Epoch 247/500
1824/1824 - 0s - loss: 2.4226e-04
Epoch 248/500
1824/1824 - 0s - loss: 2.4330e-04
Epoch 249/500
1824/1824 - 0s - loss: 2.4267e-04
Epoch 250/500
1824/1824 - 0s - loss: 2.4193e-04
Epoch 251/500
1824/1824 - 0s - loss: 2.4085e-04
Epoch 252/500
1824/1824 - 0s - loss: 2.4053e-04
Epoch 253/500
1824/1824 - 0s - loss: 2.3984e-04
Epoch 254/500
1824/1824 - 0s - loss: 2.3993e-04
Epoch 255/500
1824/1824 - 0s - loss: 2.3943e-04
Epoch 256/500
1824/1824 - 0s - loss: 2.3960e-04
Epoch 257/500
1824/1824 - 0s - loss: 2.3920e-04
Epoch 258/500
1824/1824 - 0s - loss: 2.3948e-04
Epoch 259/500
1824/1824 - 0s - loss: 2.3918e-04
Epoch 260/500
1824/1824 - 0s - loss: 2.3955e-04
Epoch 261/500
1824/1824 - 0s - loss: 2.3934e-04
Epoch 262/500
1824/1824 - 0s - loss: 2.3969e-04
Epoch 263/500
1824/1824 - 0s - loss: 2.3943e-04
Epoch 264/500
1824/1824 - 0s - loss: 2.3965e-04
Epoch 265/500
1824/1824 - 0s - loss: 2.3950e-04
Epoch 266/500
1824/1824 - 0s - loss: 2.3986e-04
Epoch 267/500
1824/1824 - 0s - loss: 2.3994e-04
Epoch 268/500
1824/1824 - 0s - loss: 2.4004e-04
Epoch 269/500
1824/1824 - 0s - loss: 2.4012e-04
Epoch 270/500
1824/1824 - 0s - loss: 2.4010e-04
Epoch 271/500
1824/1824 - 0s - loss: 2.3994e-04
Epoch 272/500
1824/1824 - 0s - loss: 2.4016e-04
Epoch 273/500
1824/1824 - 0s - loss: 2.3997e-04
Epoch 274/500
1824/1824 - 0s - loss: 2.3996e-04
Epoch 275/500
1824/1824 - 0s - loss: 2.3993e-04
Epoch 276/500
1824/1824 - 0s - loss: 2.3999e-04
Epoch 277/500
1824/1824 - 0s - loss: 2.3974e-04
Epoch 278/500
1824/1824 - 0s - loss: 2.3980e-04
Epoch 279/500
1824/1824 - 0s - loss: 2.3974e-04
Epoch 280/500
1824/1824 - 0s - loss: 2.3986e-04
Epoch 281/500
1824/1824 - 0s - loss: 2.3974e-04
Epoch 282/500
1824/1824 - 0s - loss: 2.3979e-04
Epoch 283/500
1824/1824 - 0s - loss: 2.3969e-04
Epoch 284/500
1824/1824 - 0s - loss: 2.3964e-04
Epoch 285/500
1824/1824 - 0s - loss: 2.3947e-04
Epoch 286/500
1824/1824 - 0s - loss: 2.3963e-04
Epoch 287/500
1824/1824 - 0s - loss: 2.3950e-04
Epoch 288/500
1824/1824 - 0s - loss: 2.3957e-04
Epoch 289/500
1824/1824 - 0s - loss: 2.3939e-04
Epoch 290/500
1824/1824 - 0s - loss: 2.3945e-04
Epoch 291/500
1824/1824 - 0s - loss: 2.3938e-04
Epoch 292/500
1824/1824 - 0s - loss: 2.3957e-04
Epoch 293/500
1824/1824 - 0s - loss: 2.3933e-04
Epoch 294/500
1824/1824 - 0s - loss: 2.3945e-04
Epoch 295/500
1824/1824 - 0s - loss: 2.3924e-04
Epoch 296/500
1824/1824 - 0s - loss: 2.3929e-04
Epoch 297/500
1824/1824 - 0s - loss: 2.3919e-04
Epoch 298/500
1824/1824 - 0s - loss: 2.3929e-04
Epoch 299/500
1824/1824 - 0s - loss: 2.3910e-04
Epoch 300/500
1824/1824 - 0s - loss: 2.3926e-04
Epoch 301/500
1824/1824 - 0s - loss: 2.3919e-04
Epoch 302/500
1824/1824 - 0s - loss: 2.3942e-04
Epoch 303/500
1824/1824 - 0s - loss: 2.3929e-04
Epoch 304/500
1824/1824 - 0s - loss: 2.3948e-04
Epoch 305/500
1824/1824 - 0s - loss: 2.3933e-04
Epoch 306/500
1824/1824 - 0s - loss: 2.3954e-04
Epoch 307/500
1824/1824 - 0s - loss: 2.3929e-04
Epoch 308/500
1824/1824 - 0s - loss: 2.3939e-04
Epoch 309/500
1824/1824 - 0s - loss: 2.3912e-04
Epoch 310/500
1824/1824 - 0s - loss: 2.3929e-04
Epoch 311/500
1824/1824 - 0s - loss: 2.3899e-04
Epoch 312/500
1824/1824 - 0s - loss: 2.3919e-04
Epoch 313/500
1824/1824 - 0s - loss: 2.3895e-04
Epoch 314/500
1824/1824 - 0s - loss: 2.3911e-04
Epoch 315/500
1824/1824 - 0s - loss: 2.3874e-04
Epoch 316/500
1824/1824 - 0s - loss: 2.3889e-04
Epoch 317/500
1824/1824 - 0s - loss: 2.3865e-04
Epoch 318/500
1824/1824 - 0s - loss: 2.3886e-04
Epoch 319/500
1824/1824 - 0s - loss: 2.3864e-04
Epoch 320/500
1824/1824 - 0s - loss: 2.3884e-04
Epoch 321/500
1824/1824 - 0s - loss: 2.3857e-04
Epoch 322/500
1824/1824 - 0s - loss: 2.3875e-04
Epoch 323/500
1824/1824 - 0s - loss: 2.3851e-04
Epoch 324/500
1824/1824 - 0s - loss: 2.3873e-04
Epoch 325/500
1824/1824 - 0s - loss: 2.3856e-04
Epoch 326/500
1824/1824 - 0s - loss: 2.3872e-04
Epoch 327/500
1824/1824 - 0s - loss: 2.3843e-04
Epoch 328/500
1824/1824 - 0s - loss: 2.3863e-04
Epoch 329/500
1824/1824 - 0s - loss: 2.3841e-04
Epoch 330/500
1824/1824 - 0s - loss: 2.3856e-04
Epoch 331/500
1824/1824 - 0s - loss: 2.3838e-04
Epoch 332/500
1824/1824 - 0s - loss: 2.3853e-04
Epoch 333/500
1824/1824 - 0s - loss: 2.3828e-04
Epoch 334/500
1824/1824 - 0s - loss: 2.3845e-04
Epoch 335/500
1824/1824 - 0s - loss: 2.3821e-04
Epoch 336/500
1824/1824 - 0s - loss: 2.3841e-04
Epoch 337/500
1824/1824 - 0s - loss: 2.3823e-04
Epoch 338/500
1824/1824 - 0s - loss: 2.3848e-04
Epoch 339/500
1824/1824 - 0s - loss: 2.3820e-04
Epoch 340/500
1824/1824 - 0s - loss: 2.3836e-04
Epoch 341/500
1824/1824 - 0s - loss: 2.3810e-04
Epoch 342/500
1824/1824 - 0s - loss: 2.3828e-04
Epoch 343/500
1824/1824 - 0s - loss: 2.3808e-04
Epoch 344/500
1824/1824 - 0s - loss: 2.3827e-04
Epoch 345/500
1824/1824 - 0s - loss: 2.3796e-04

Epoch 346/500
1824/1824 - 0s - loss: 2.3816e-04
Epoch 347/500
1824/1824 - 0s - loss: 2.3801e-04
Epoch 348/500
1824/1824 - 0s - loss: 2.3821e-04
Epoch 349/500
1824/1824 - 0s - loss: 2.3788e-04
Epoch 350/500
1824/1824 - 0s - loss: 2.3799e-04
Epoch 351/500
1824/1824 - 0s - loss: 2.3784e-04
Epoch 352/500
1824/1824 - 0s - loss: 2.3805e-04
Epoch 353/500
1824/1824 - 0s - loss: 2.3773e-04
Epoch 354/500
1824/1824 - 0s - loss: 2.3791e-04
Epoch 355/500
1824/1824 - 0s - loss: 2.3780e-04
Epoch 356/500
1824/1824 - 0s - loss: 2.3796e-04
Epoch 357/500
1824/1824 - 0s - loss: 2.3764e-04
Epoch 358/500
1824/1824 - 0s - loss: 2.3778e-04
Epoch 359/500
1824/1824 - 0s - loss: 2.3761e-04
Epoch 360/500
1824/1824 - 0s - loss: 2.3782e-04
Epoch 361/500
1824/1824 - 0s - loss: 2.3756e-04
Epoch 362/500
1824/1824 - 0s - loss: 2.3774e-04
Epoch 363/500
1824/1824 - 0s - loss: 2.3749e-04
Epoch 364/500
1824/1824 - 0s - loss: 2.3766e-04
Epoch 365/500
1824/1824 - 0s - loss: 2.3742e-04
Epoch 366/500
1824/1824 - 0s - loss: 2.3765e-04
Epoch 367/500
1824/1824 - 0s - loss: 2.3742e-04
Epoch 368/500
1824/1824 - 0s - loss: 2.3755e-04
Epoch 369/500
1824/1824 - 0s - loss: 2.3736e-04
Epoch 370/500
1824/1824 - 0s - loss: 2.3754e-04
Epoch 371/500
1824/1824 - 0s - loss: 2.3727e-04
Epoch 372/500
1824/1824 - 0s - loss: 2.3742e-04
Epoch 373/500
1824/1824 - 0s - loss: 2.3731e-04
Epoch 374/500
1824/1824 - 0s - loss: 2.3749e-04
Epoch 375/500
1824/1824 - 0s - loss: 2.3723e-04
Epoch 376/500
1824/1824 - 0s - loss: 2.3738e-04
Epoch 377/500
1824/1824 - 0s - loss: 2.3719e-04
Epoch 378/500
1824/1824 - 0s - loss: 2.3737e-04
Epoch 379/500
1824/1824 - 0s - loss: 2.3721e-04
Epoch 380/500
1824/1824 - 0s - loss: 2.3739e-04
Epoch 381/500
1824/1824 - 0s - loss: 2.3717e-04
Epoch 382/500
1824/1824 - 0s - loss: 2.3730e-04
Epoch 383/500
1824/1824 - 0s - loss: 2.3713e-04
Epoch 384/500
1824/1824 - 0s - loss: 2.3735e-04
Epoch 385/500
1824/1824 - 0s - loss: 2.3713e-04
Epoch 386/500
1824/1824 - 0s - loss: 2.3722e-04
Epoch 387/500
1824/1824 - 0s - loss: 2.3704e-04
Epoch 388/500
1824/1824 - 0s - loss: 2.3728e-04
Epoch 389/500
1824/1824 - 0s - loss: 2.3737e-04
Epoch 390/500
1824/1824 - 0s - loss: 2.3757e-04
Epoch 391/500
1824/1824 - 0s - loss: 2.3777e-04
Epoch 392/500
1824/1824 - 0s - loss: 2.3804e-04
Epoch 393/500
1824/1824 - 0s - loss: 2.3804e-04
Epoch 394/500
1824/1824 - 0s - loss: 2.3833e-04
Epoch 395/500
1824/1824 - 0s - loss: 2.3802e-04
Epoch 396/500
1824/1824 - 0s - loss: 2.3802e-04
Epoch 397/500
1824/1824 - 0s - loss: 2.3783e-04
Epoch 398/500
1824/1824 - 0s - loss: 2.3788e-04
Epoch 399/500
1824/1824 - 0s - loss: 2.3751e-04
Epoch 400/500
1824/1824 - 0s - loss: 2.3733e-04
Epoch 401/500
1824/1824 - 0s - loss: 2.3716e-04
Epoch 402/500
1824/1824 - 0s - loss: 2.3736e-04
Epoch 403/500
1824/1824 - 0s - loss: 2.3733e-04
Epoch 404/500
1824/1824 - 0s - loss: 2.3737e-04
Epoch 405/500
1824/1824 - 0s - loss: 2.3729e-04
Epoch 406/500
1824/1824 - 0s - loss: 2.3736e-04
Epoch 407/500
1824/1824 - 0s - loss: 2.3695e-04
Epoch 408/500
1824/1824 - 0s - loss: 2.3691e-04
Epoch 409/500
1824/1824 - 0s - loss: 2.3683e-04
Epoch 410/500
1824/1824 - 0s - loss: 2.3696e-04
Epoch 411/500
1824/1824 - 0s - loss: 2.3676e-04
Epoch 412/500
1824/1824 - 0s - loss: 2.3676e-04
Epoch 413/500
1824/1824 - 0s - loss: 2.3673e-04
Epoch 414/500
1824/1824 - 0s - loss: 2.3696e-04
Epoch 415/500
1824/1824 - 0s - loss: 2.3682e-04
Epoch 416/500
1824/1824 - 0s - loss: 2.3694e-04
Epoch 417/500
1824/1824 - 0s - loss: 2.3685e-04
Epoch 418/500
1824/1824 - 0s - loss: 2.3701e-04
Epoch 419/500
1824/1824 - 0s - loss: 2.3675e-04
Epoch 420/500
1824/1824 - 0s - loss: 2.3685e-04
Epoch 421/500
1824/1824 - 0s - loss: 2.3675e-04
Epoch 422/500
1824/1824 - 0s - loss: 2.3683e-04
Epoch 423/500
1824/1824 - 0s - loss: 2.3663e-04
Epoch 424/500
1824/1824 - 0s - loss: 2.3670e-04
Epoch 425/500
1824/1824 - 0s - loss: 2.3661e-04
Epoch 426/500
1824/1824 - 0s - loss: 2.3677e-04
Epoch 427/500
1824/1824 - 0s - loss: 2.3658e-04
Epoch 428/500
1824/1824 - 0s - loss: 2.3656e-04
Epoch 429/500
1824/1824 - 0s - loss: 2.3644e-04
Epoch 430/500
1824/1824 - 0s - loss: 2.3662e-04
Epoch 431/500
1824/1824 - 0s - loss: 2.3650e-04
Epoch 432/500
1824/1824 - 0s - loss: 2.3656e-04
Epoch 433/500
1824/1824 - 0s - loss: 2.3637e-04
Epoch 434/500
1824/1824 - 0s - loss: 2.3650e-04
Epoch 435/500
1824/1824 - 0s - loss: 2.3644e-04
Epoch 436/500
1824/1824 - 0s - loss: 2.3659e-04
Epoch 437/500
1824/1824 - 0s - loss: 2.3625e-04
Epoch 438/500
1824/1824 - 0s - loss: 2.3626e-04
Epoch 439/500
1824/1824 - 0s - loss: 2.3628e-04
Epoch 440/500
1824/1824 - 0s - loss: 2.3649e-04
Epoch 441/500
1824/1824 - 0s - loss: 2.3625e-04
Epoch 442/500
1824/1824 - 0s - loss: 2.3624e-04
Epoch 443/500
1824/1824 - 0s - loss: 2.3629e-04
Epoch 444/500
1824/1824 - 0s - loss: 2.3656e-04
Epoch 445/500
1824/1824 - 0s - loss: 2.3633e-04
Epoch 446/500
1824/1824 - 0s - loss: 2.3629e-04
Epoch 447/500
1824/1824 - 0s - loss: 2.3631e-04
Epoch 448/500
1824/1824 - 0s - loss: 2.3660e-04
Epoch 449/500
1824/1824 - 0s - loss: 2.3615e-04
Epoch 450/500
1824/1824 - 0s - loss: 2.3621e-04
Epoch 451/500
1824/1824 - 0s - loss: 2.3608e-04
Epoch 452/500
1824/1824 - 0s - loss: 2.3639e-04
Epoch 453/500
1824/1824 - 0s - loss: 2.3602e-04
Epoch 454/500
1824/1824 - 0s - loss: 2.3608e-04
Epoch 455/500
1824/1824 - 0s - loss: 2.3597e-04
Epoch 456/500
1824/1824 - 0s - loss: 2.3615e-04
Epoch 457/500
1824/1824 - 0s - loss: 2.3592e-04
Epoch 458/500
1824/1824 - 0s - loss: 2.3595e-04
Epoch 459/500
1824/1824 - 0s - loss: 2.3592e-04
Epoch 460/500
1824/1824 - 0s - loss: 2.3609e-04
Epoch 461/500
1824/1824 - 0s - loss: 2.3595e-04
Epoch 462/500
1824/1824 - 0s - loss: 2.3606e-04
Epoch 463/500
1824/1824 - 0s - loss: 2.3585e-04
Epoch 464/500
1824/1824 - 0s - loss: 2.3600e-04
Epoch 465/500
1824/1824 - 0s - loss: 2.3582e-04
Epoch 466/500
1824/1824 - 0s - loss: 2.3602e-04
Epoch 467/500
1824/1824 - 0s - loss: 2.3581e-04
Epoch 468/500
1824/1824 - 0s - loss: 2.3591e-04
Epoch 469/500
1824/1824 - 0s - loss: 2.3567e-04
Epoch 470/500
1824/1824 - 0s - loss: 2.3591e-04
Epoch 471/500
1824/1824 - 0s - loss: 2.3573e-04
Epoch 472/500
1824/1824 - 0s - loss: 2.3582e-04
Epoch 473/500
1824/1824 - 0s - loss: 2.3553e-04
Epoch 474/500
1824/1824 - 0s - loss: 2.3578e-04
Epoch 475/500
1824/1824 - 0s - loss: 2.3566e-04
Epoch 476/500
1824/1824 - 0s - loss: 2.3579e-04
Epoch 477/500
1824/1824 - 0s - loss: 2.3548e-04
Epoch 478/500
1824/1824 - 0s - loss: 2.3560e-04
Epoch 479/500
1824/1824 - 0s - loss: 2.3542e-04
Epoch 480/500
1824/1824 - 0s - loss: 2.3565e-04
Epoch 481/500
1824/1824 - 0s - loss: 2.3546e-04
Epoch 482/500
1824/1824 - 0s - loss: 2.3555e-04
Epoch 483/500
1824/1824 - 0s - loss: 2.3528e-04
Epoch 484/500
1824/1824 - 0s - loss: 2.3546e-04
Epoch 485/500
1824/1824 - 0s - loss: 2.3535e-04
Epoch 486/500
1824/1824 - 0s - loss: 2.3552e-04
Epoch 487/500
1824/1824 - 0s - loss: 2.3541e-04
Epoch 488/500
1824/1824 - 0s - loss: 2.3539e-04
Epoch 489/500
1824/1824 - 0s - loss: 2.3515e-04
Epoch 490/500
1824/1824 - 0s - loss: 2.3521e-04
Epoch 491/500
1824/1824 - 0s - loss: 2.3529e-04
Epoch 492/500
1824/1824 - 0s - loss: 2.3542e-04
Epoch 493/500
1824/1824 - 0s - loss: 2.3518e-04
Epoch 494/500
1824/1824 - 0s - loss: 2.3510e-04
Epoch 495/500
1824/1824 - 0s - loss: 2.3509e-04
Epoch 496/500
1824/1824 - 0s - loss: 2.3531e-04
Epoch 497/500
1824/1824 - 0s - loss: 2.3517e-04
Epoch 498/500
1824/1824 - 0s - loss: 2.3506e-04
Epoch 499/500
1824/1824 - 0s - loss: 2.3494e-04
Epoch 500/500
1824/1824 - 0s - loss: 2.3511e-04

In [6]:

model=load_model('BM.h5') 
trainPredict = model.predict(X)
testPredict = scaler.inverse_transform(trainPredict)
testY = scaler.inverse_transform(y)
df_BM['Bit_T']=pd.DataFrame(testPredict[:,0],columns=['Bit_T'])
df_BM.dropna(inplace=True)
df_BM

         Date     Value         Bit_T
0     9/11/16    621.65    803.767822
1     9/12/16    609.67    792.848755
2     9/13/16    610.92    793.668823
3     9/14/16    608.82    792.291382
4     9/15/16    610.38    793.314575
...       ...       ...           ...
1819   9/4/21  50035.33  51142.750000
1820   9/5/21  49947.38  51053.761719
1821   9/6/21  51769.06  52900.636719
1822   9/7/21  52677.40  53824.527344
1823   9/8/21  46809.17  47890.578125

[1824 rows x 3 columns]

In [7]:
df_GOLD.dropna(inplace=True)
dataset = df_GOLD['USD (PM)'].values

dataset = dataset.astype('float32').reshape(-1, 1) 

scaler = MinMaxScaler(feature_range=(0, 1))
dataset=scaler.fit_transform(dataset).astype('float32')
X,y,x_input_last,n_steps=lstm(dataset,1,'gold.h5')

Train on 1253 samples
Epoch 1/500
1253/1253 - 2s - loss: 0.1509
Epoch 2/500
1253/1253 - 0s - loss: 0.0891
Epoch 3/500
1253/1253 - 0s - loss: 0.0505
Epoch 4/500
1253/1253 - 0s - loss: 0.0431
Epoch 5/500
1253/1253 - 0s - loss: 0.0416
Epoch 6/500
1253/1253 - 0s - loss: 0.0362
Epoch 7/500
1253/1253 - 0s - loss: 0.0300
Epoch 8/500
1253/1253 - 0s - loss: 0.0239
Epoch 9/500
1253/1253 - 0s - loss: 0.0181
Epoch 10/500
1253/1253 - 0s - loss: 0.0131
Epoch 11/500
1253/1253 - 0s - loss: 0.0089
Epoch 12/500
1253/1253 - 0s - loss: 0.0058
Epoch 13/500
1253/1253 - 0s - loss: 0.0038
Epoch 14/500
1253/1253 - 0s - loss: 0.0026
Epoch 15/500
1253/1253 - 0s - loss: 0.0018
Epoch 16/500
1253/1253 - 0s - loss: 0.0014
Epoch 17/500
1253/1253 - 0s - loss: 0.0013
Epoch 18/500
1253/1253 - 0s - loss: 0.0012
Epoch 19/500
1253/1253 - 0s - loss: 0.0012
Epoch 20/500
1253/1253 - 0s - loss: 0.0012
Epoch 21/500
1253/1253 - 0s - loss: 0.0012
Epoch 22/500
1253/1253 - 0s - loss: 0.0012
Epoch 23/500
1253/1253 - 0s - loss: 0.0012
Epoch 24/500
1253/1253 - 0s - loss: 0.0011
Epoch 25/500
1253/1253 - 0s - loss: 0.0011
Epoch 26/500
1253/1253 - 0s - loss: 0.0011
Epoch 27/500
1253/1253 - 0s - loss: 0.0011
Epoch 28/500
1253/1253 - 0s - loss: 0.0011
Epoch 29/500
1253/1253 - 0s - loss: 0.0011
Epoch 30/500
1253/1253 - 0s - loss: 0.0011
Epoch 31/500
1253/1253 - 0s - loss: 0.0011
Epoch 32/500
1253/1253 - 0s - loss: 0.0010
Epoch 33/500
1253/1253 - 0s - loss: 0.0010
Epoch 34/500
1253/1253 - 0s - loss: 0.0010
Epoch 35/500
1253/1253 - 0s - loss: 9.7717e-04
Epoch 36/500
1253/1253 - 0s - loss: 9.4249e-04
Epoch 37/500
1253/1253 - 0s - loss: 9.1117e-04
Epoch 38/500
1253/1253 - 0s - loss: 8.7509e-04
Epoch 39/500
1253/1253 - 0s - loss: 8.3828e-04
Epoch 40/500
1253/1253 - 0s - loss: 8.0553e-04
Epoch 41/500
1253/1253 - 0s - loss: 7.7535e-04
Epoch 42/500
1253/1253 - 0s - loss: 7.4442e-04
Epoch 43/500
1253/1253 - 0s - loss: 7.1294e-04
Epoch 44/500
1253/1253 - 0s - loss: 6.8168e-04
Epoch 45/500
1253/1253 - 0s - loss: 6.5017e-04
Epoch 46/500
1253/1253 - 0s - loss: 6.1867e-04
Epoch 47/500
1253/1253 - 0s - loss: 5.8730e-04
Epoch 48/500
1253/1253 - 0s - loss: 5.5640e-04
Epoch 49/500
1253/1253 - 0s - loss: 5.2635e-04
Epoch 50/500
1253/1253 - 0s - loss: 4.9709e-04
Epoch 51/500
1253/1253 - 0s - loss: 4.6899e-04
Epoch 52/500
1253/1253 - 0s - loss: 4.4346e-04
Epoch 53/500
1253/1253 - 0s - loss: 4.2022e-04
Epoch 54/500
1253/1253 - 0s - loss: 4.0116e-04
Epoch 55/500
1253/1253 - 0s - loss: 3.8753e-04
Epoch 56/500
1253/1253 - 0s - loss: 3.8132e-04
Epoch 57/500
1253/1253 - 0s - loss: 3.8462e-04
Epoch 58/500
1253/1253 - 0s - loss: 3.9839e-04
Epoch 59/500
1253/1253 - 0s - loss: 4.1961e-04
Epoch 60/500
1253/1253 - 0s - loss: 4.4227e-04
Epoch 61/500
1253/1253 - 0s - loss: 4.5732e-04
Epoch 62/500
1253/1253 - 0s - loss: 4.5594e-04
Epoch 63/500
1253/1253 - 0s - loss: 4.3772e-04
Epoch 64/500
1253/1253 - 0s - loss: 4.0589e-04
Epoch 65/500
1253/1253 - 0s - loss: 3.6583e-04
Epoch 66/500
1253/1253 - 0s - loss: 3.3246e-04
Epoch 67/500
1253/1253 - 0s - loss: 3.0899e-04
Epoch 68/500
1253/1253 - 0s - loss: 2.9382e-04
Epoch 69/500
1253/1253 - 0s - loss: 2.8282e-04
Epoch 70/500
1253/1253 - 0s - loss: 2.7499e-04
Epoch 71/500
1253/1253 - 0s - loss: 2.6931e-04
Epoch 72/500
1253/1253 - 0s - loss: 2.6681e-04
Epoch 73/500
1253/1253 - 0s - loss: 2.6808e-04
Epoch 74/500
1253/1253 - 0s - loss: 2.7526e-04
Epoch 75/500
1253/1253 - 0s - loss: 2.9184e-04
Epoch 76/500
1253/1253 - 0s - loss: 3.2164e-04
Epoch 77/500
1253/1253 - 0s - loss: 3.6713e-04
Epoch 78/500
1253/1253 - 0s - loss: 4.2386e-04
Epoch 79/500
1253/1253 - 0s - loss: 5.0172e-04
Epoch 80/500
1253/1253 - 0s - loss: 5.7123e-04
Epoch 81/500
1253/1253 - 0s - loss: 5.6010e-04
Epoch 82/500
1253/1253 - 0s - loss: 4.5325e-04
Epoch 83/500
1253/1253 - 0s - loss: 3.5314e-04
Epoch 84/500
1253/1253 - 0s - loss: 2.8957e-04
Epoch 85/500
1253/1253 - 0s - loss: 2.5875e-04
Epoch 86/500
1253/1253 - 0s - loss: 2.6486e-04
Epoch 87/500
1253/1253 - 0s - loss: 3.2365e-04
Epoch 88/500
1253/1253 - 0s - loss: 4.9854e-04
Epoch 89/500
1253/1253 - 0s - loss: 9.1095e-04
Epoch 90/500
1253/1253 - 0s - loss: 0.0017
Epoch 91/500
1253/1253 - 0s - loss: 0.0031
Epoch 92/500
1253/1253 - 0s - loss: 0.0042
Epoch 93/500
1253/1253 - 0s - loss: 0.0037
Epoch 94/500
1253/1253 - 0s - loss: 0.0022
Epoch 95/500
1253/1253 - 0s - loss: 8.8368e-04
Epoch 96/500
1253/1253 - 0s - loss: 3.8353e-04
Epoch 97/500
1253/1253 - 0s - loss: 2.6411e-04
Epoch 98/500
1253/1253 - 0s - loss: 2.5407e-04
Epoch 99/500
1253/1253 - 0s - loss: 2.6711e-04
Epoch 100/500
1253/1253 - 0s - loss: 2.7644e-04
Epoch 101/500
1253/1253 - 0s - loss: 2.7707e-04
Epoch 102/500
1253/1253 - 0s - loss: 2.6932e-04
Epoch 103/500
1253/1253 - 0s - loss: 2.5641e-04
Epoch 104/500
1253/1253 - 0s - loss: 2.4351e-04
Epoch 105/500
1253/1253 - 0s - loss: 2.3326e-04
Epoch 106/500
1253/1253 - 0s - loss: 2.2710e-04
Epoch 107/500
1253/1253 - 0s - loss: 2.2507e-04
Epoch 108/500
1253/1253 - 0s - loss: 2.2719e-04
Epoch 109/500
1253/1253 - 0s - loss: 2.3310e-04
Epoch 110/500
1253/1253 - 0s - loss: 2.4239e-04
Epoch 111/500
1253/1253 - 0s - loss: 2.5449e-04
Epoch 112/500
1253/1253 - 0s - loss: 2.6994e-04
Epoch 113/500
1253/1253 - 0s - loss: 2.9084e-04
Epoch 114/500
1253/1253 - 0s - loss: 3.1993e-04
Epoch 115/500
1253/1253 - 0s - loss: 3.6219e-04
Epoch 116/500
1253/1253 - 0s - loss: 4.2435e-04
Epoch 117/500
1253/1253 - 0s - loss: 5.1919e-04
Epoch 118/500
1253/1253 - 0s - loss: 6.6164e-04
Epoch 119/500
1253/1253 - 0s - loss: 8.7768e-04
Epoch 120/500
1253/1253 - 0s - loss: 0.0012
Epoch 121/500
1253/1253 - 0s - loss: 0.0016
Epoch 122/500
1253/1253 - 0s - loss: 0.0019
Epoch 123/500
1253/1253 - 0s - loss: 0.0020
Epoch 124/500
1253/1253 - 0s - loss: 0.0017
Epoch 125/500
1253/1253 - 0s - loss: 0.0012
Epoch 126/500
1253/1253 - 0s - loss: 7.4025e-04
Epoch 127/500
1253/1253 - 0s - loss: 4.5307e-04
Epoch 128/500
1253/1253 - 0s - loss: 3.1840e-04
Epoch 129/500
1253/1253 - 0s - loss: 2.8060e-04
Epoch 130/500
1253/1253 - 0s - loss: 2.9457e-04
Epoch 131/500
1253/1253 - 0s - loss: 3.3159e-04
Epoch 132/500
1253/1253 - 0s - loss: 3.7355e-04
Epoch 133/500
1253/1253 - 0s - loss: 4.0846e-04
Epoch 134/500
1253/1253 - 0s - loss: 4.2132e-04
Epoch 135/500
1253/1253 - 0s - loss: 3.7307e-04
Epoch 136/500
1253/1253 - 0s - loss: 3.7990e-04
Epoch 137/500
1253/1253 - 0s - loss: 3.1821e-04
Epoch 138/500
1253/1253 - 0s - loss: 2.7415e-04
Epoch 139/500
1253/1253 - 0s - loss: 2.4159e-04
Epoch 140/500
1253/1253 - 0s - loss: 2.3000e-04
Epoch 141/500
1253/1253 - 0s - loss: 2.4087e-04
Epoch 142/500
1253/1253 - 0s - loss: 2.7424e-04
Epoch 143/500
1253/1253 - 0s - loss: 3.3581e-04
Epoch 144/500
1253/1253 - 0s - loss: 4.3360e-04
Epoch 145/500
1253/1253 - 0s - loss: 5.8342e-04
Epoch 146/500
1253/1253 - 0s - loss: 8.0806e-04
Epoch 147/500
1253/1253 - 0s - loss: 0.0011
Epoch 148/500
1253/1253 - 0s - loss: 0.0016
Epoch 149/500
1253/1253 - 0s - loss: 0.0020
Epoch 150/500
1253/1253 - 0s - loss: 0.0021
Epoch 151/500
1253/1253 - 0s - loss: 0.0019
Epoch 152/500
1253/1253 - 0s - loss: 0.0013
Epoch 153/500
1253/1253 - 0s - loss: 7.7755e-04
Epoch 154/500
1253/1253 - 0s - loss: 4.5840e-04
Epoch 155/500
1253/1253 - 0s - loss: 3.1715e-04
Epoch 156/500
1253/1253 - 0s - loss: 2.8035e-04
Epoch 157/500
1253/1253 - 0s - loss: 2.9647e-04
Epoch 158/500
1253/1253 - 0s - loss: 3.3338e-04
Epoch 159/500
1253/1253 - 0s - loss: 3.7529e-04
Epoch 160/500
1253/1253 - 0s - loss: 4.0526e-04
Epoch 161/500
1253/1253 - 0s - loss: 4.1386e-04
Epoch 162/500
1253/1253 - 0s - loss: 3.9619e-04
Epoch 163/500
1253/1253 - 0s - loss: 3.5628e-04
Epoch 164/500
1253/1253 - 0s - loss: 3.0640e-04
Epoch 165/500
1253/1253 - 0s - loss: 2.6386e-04
Epoch 166/500
1253/1253 - 0s - loss: 2.3784e-04
Epoch 167/500
1253/1253 - 0s - loss: 2.3190e-04
Epoch 168/500
1253/1253 - 0s - loss: 2.4671e-04
Epoch 169/500
1253/1253 - 0s - loss: 2.8199e-04
Epoch 170/500
1253/1253 - 0s - loss: 3.4000e-04
Epoch 171/500
1253/1253 - 0s - loss: 4.2858e-04
Epoch 172/500
1253/1253 - 0s - loss: 5.5758e-04
Epoch 173/500
1253/1253 - 0s - loss: 7.4252e-04
Epoch 174/500
1253/1253 - 0s - loss: 0.0010
Epoch 175/500
1253/1253 - 0s - loss: 0.0013
Epoch 176/500
1253/1253 - 0s - loss: 0.0017
Epoch 177/500
1253/1253 - 0s - loss: 0.0018
Epoch 178/500
1253/1253 - 0s - loss: 0.0017

Epoch 179/500
1253/1253 - 0s - loss: 0.0013
Epoch 180/500
1253/1253 - 0s - loss: 8.3143e-04
Epoch 181/500
1253/1253 - 0s - loss: 5.1604e-04
Epoch 182/500
1253/1253 - 0s - loss: 3.5003e-04
Epoch 183/500
1253/1253 - 0s - loss: 2.8703e-04
Epoch 184/500
1253/1253 - 0s - loss: 2.8432e-04
Epoch 185/500
1253/1253 - 0s - loss: 3.1229e-04
Epoch 186/500
1253/1253 - 0s - loss: 3.5456e-04
Epoch 187/500
1253/1253 - 0s - loss: 3.9503e-04
Epoch 188/500
1253/1253 - 0s - loss: 4.2408e-04
Epoch 189/500
1253/1253 - 0s - loss: 4.2949e-04
Epoch 190/500
1253/1253 - 0s - loss: 4.1134e-04
Epoch 191/500
1253/1253 - 0s - loss: 3.6725e-04
Epoch 192/500
1253/1253 - 0s - loss: 3.1608e-04
Epoch 193/500
1253/1253 - 0s - loss: 2.7469e-04
Epoch 194/500
1253/1253 - 0s - loss: 2.4786e-04
Epoch 195/500
1253/1253 - 0s - loss: 2.3483e-04
Epoch 196/500
1253/1253 - 0s - loss: 2.3802e-04
Epoch 197/500
1253/1253 - 0s - loss: 2.5940e-04
Epoch 198/500
1253/1253 - 0s - loss: 3.0249e-04
Epoch 199/500
1253/1253 - 0s - loss: 3.7914e-04
Epoch 200/500
1253/1253 - 0s - loss: 5.0403e-04
Epoch 201/500
1253/1253 - 0s - loss: 6.9654e-04
Epoch 202/500
1253/1253 - 0s - loss: 9.8783e-04
Epoch 203/500
1253/1253 - 0s - loss: 0.0014
Epoch 204/500
1253/1253 - 0s - loss: 0.0019
Epoch 205/500
1253/1253 - 0s - loss: 0.0021
Epoch 206/500
1253/1253 - 0s - loss: 0.0019
Epoch 207/500
1253/1253 - 0s - loss: 0.0014
Epoch 208/500
1253/1253 - 0s - loss: 8.2342e-04
Epoch 209/500
1253/1253 - 0s - loss: 4.7311e-04
Epoch 210/500
1253/1253 - 0s - loss: 3.2085e-04
Epoch 211/500
1253/1253 - 0s - loss: 2.8404e-04
Epoch 212/500
1253/1253 - 0s - loss: 3.0176e-04
Epoch 213/500
1253/1253 - 0s - loss: 3.4039e-04
Epoch 214/500
1253/1253 - 0s - loss: 3.8028e-04
Epoch 215/500
1253/1253 - 0s - loss: 4.0714e-04
Epoch 216/500
1253/1253 - 0s - loss: 4.1476e-04
Epoch 217/500
1253/1253 - 0s - loss: 3.9768e-04
Epoch 218/500
1253/1253 - 0s - loss: 3.5700e-04
Epoch 219/500
1253/1253 - 0s - loss: 3.0913e-04
Epoch 220/500
1253/1253 - 0s - loss: 2.7103e-04
Epoch 221/500
1253/1253 - 0s - loss: 2.4701e-04
Epoch 222/500
1253/1253 - 0s - loss: 2.3605e-04
Epoch 223/500
1253/1253 - 0s - loss: 2.3927e-04
Epoch 224/500
1253/1253 - 0s - loss: 2.5783e-04
Epoch 225/500
1253/1253 - 0s - loss: 2.9393e-04
Epoch 226/500
1253/1253 - 0s - loss: 3.5218e-04
Epoch 227/500
1253/1253 - 0s - loss: 4.4147e-04
Epoch 228/500
1253/1253 - 0s - loss: 5.7616e-04
Epoch 229/500
1253/1253 - 0s - loss: 7.6539e-04
Epoch 230/500
1253/1253 - 0s - loss: 0.0010
Epoch 231/500
1253/1253 - 0s - loss: 0.0013
Epoch 232/500
1253/1253 - 0s - loss: 0.0016
Epoch 233/500
1253/1253 - 0s - loss: 0.0016
Epoch 234/500
1253/1253 - 0s - loss: 0.0014
Epoch 235/500
1253/1253 - 0s - loss: 0.0010
Epoch 236/500
1253/1253 - 0s - loss: 6.7398e-04
Epoch 237/500
1253/1253 - 0s - loss: 4.3897e-04
Epoch 238/500
1253/1253 - 0s - loss: 3.2183e-04
Epoch 239/500
1253/1253 - 0s - loss: 2.8346e-04
Epoch 240/500
1253/1253 - 0s - loss: 2.9062e-04
Epoch 241/500
1253/1253 - 0s - loss: 3.0660e-04
Epoch 242/500
1253/1253 - 0s - loss: 3.6501e-04
Epoch 243/500
1253/1253 - 0s - loss: 3.9898e-04
Epoch 244/500
1253/1253 - 0s - loss: 4.2931e-04
Epoch 245/500
1253/1253 - 0s - loss: 4.3889e-04
Epoch 246/500
1253/1253 - 0s - loss: 4.1747e-04
Epoch 247/500
1253/1253 - 0s - loss: 3.8170e-04
Epoch 248/500
1253/1253 - 0s - loss: 3.4434e-04
Epoch 249/500
1253/1253 - 0s - loss: 3.0945e-04
Epoch 250/500
1253/1253 - 0s - loss: 2.7923e-04
Epoch 251/500
1253/1253 - 0s - loss: 2.5703e-04
Epoch 252/500
1253/1253 - 0s - loss: 2.4346e-04
Epoch 253/500
1253/1253 - 0s - loss: 2.4121e-04
Epoch 254/500
1253/1253 - 0s - loss: 2.5401e-04
Epoch 255/500
1253/1253 - 0s - loss: 2.8676e-04
Epoch 256/500
1253/1253 - 0s - loss: 3.4951e-04
Epoch 257/500
1253/1253 - 0s - loss: 4.6411e-04
Epoch 258/500
1253/1253 - 0s - loss: 6.5887e-04
Epoch 259/500
1253/1253 - 0s - loss: 9.7667e-04
Epoch 260/500
1253/1253 - 0s - loss: 0.0015
Epoch 261/500
1253/1253 - 0s - loss: 0.0020
Epoch 262/500
1253/1253 - 0s - loss: 0.0022
Epoch 263/500
1253/1253 - 0s - loss: 0.0020
Epoch 264/500
1253/1253 - 0s - loss: 0.0013
Epoch 265/500
1253/1253 - 0s - loss: 7.0813e-04
Epoch 266/500
1253/1253 - 0s - loss: 3.9903e-04
Epoch 267/500
1253/1253 - 0s - loss: 2.9867e-04
Epoch 268/500
1253/1253 - 0s - loss: 2.9576e-04
Epoch 269/500
1253/1253 - 0s - loss: 3.2868e-04
Epoch 270/500
1253/1253 - 0s - loss: 3.6588e-04
Epoch 271/500
1253/1253 - 0s - loss: 3.9292e-04
Epoch 272/500
1253/1253 - 0s - loss: 3.9647e-04
Epoch 273/500
1253/1253 - 0s - loss: 3.7655e-04
Epoch 274/500
1253/1253 - 0s - loss: 3.3978e-04
Epoch 275/500
1253/1253 - 0s - loss: 2.9950e-04
Epoch 276/500
1253/1253 - 0s - loss: 2.6851e-04
Epoch 277/500
1253/1253 - 0s - loss: 2.4780e-04
Epoch 278/500
1253/1253 - 0s - loss: 2.3757e-04
Epoch 279/500
1253/1253 - 0s - loss: 2.3685e-04
Epoch 280/500
1253/1253 - 0s - loss: 2.4592e-04
Epoch 281/500
1253/1253 - 0s - loss: 2.6505e-04
Epoch 282/500
1253/1253 - 0s - loss: 2.9645e-04
Epoch 283/500
1253/1253 - 0s - loss: 3.4610e-04
Epoch 284/500
1253/1253 - 0s - loss: 4.1851e-04
Epoch 285/500
1253/1253 - 0s - loss: 5.2321e-04
Epoch 286/500
1253/1253 - 0s - loss: 6.7153e-04
Epoch 287/500
1253/1253 - 0s - loss: 8.7349e-04
Epoch 288/500
1253/1253 - 0s - loss: 0.0011
Epoch 289/500
1253/1253 - 0s - loss: 0.0013
Epoch 290/500
1253/1253 - 0s - loss: 0.0014
Epoch 291/500
1253/1253 - 0s - loss: 0.0013
Epoch 292/500
1253/1253 - 0s - loss: 0.0010
Epoch 293/500
1253/1253 - 0s - loss: 6.9840e-04
Epoch 294/500
1253/1253 - 0s - loss: 4.6622e-04
Epoch 295/500
1253/1253 - 0s - loss: 3.3875e-04
Epoch 296/500
1253/1253 - 0s - loss: 2.9051e-04
Epoch 297/500
1253/1253 - 0s - loss: 2.9072e-04
Epoch 298/500
1253/1253 - 0s - loss: 3.1871e-04
Epoch 299/500
1253/1253 - 0s - loss: 3.5945e-04
Epoch 300/500
1253/1253 - 0s - loss: 4.0325e-04
Epoch 301/500
1253/1253 - 0s - loss: 4.3334e-04
Epoch 302/500
1253/1253 - 0s - loss: 4.3907e-04
Epoch 303/500
1253/1253 - 0s - loss: 4.1831e-04
Epoch 304/500
1253/1253 - 0s - loss: 3.8817e-04
Epoch 305/500
1253/1253 - 0s - loss: 3.5517e-04
Epoch 306/500
1253/1253 - 0s - loss: 3.2147e-04
Epoch 307/500
1253/1253 - 0s - loss: 2.8901e-04
Epoch 308/500
1253/1253 - 0s - loss: 2.6398e-04
Epoch 309/500
1253/1253 - 0s - loss: 2.4734e-04
Epoch 310/500
1253/1253 - 0s - loss: 2.4113e-04
Epoch 311/500
1253/1253 - 0s - loss: 2.4892e-04
Epoch 312/500
1253/1253 - 0s - loss: 2.7453e-04
Epoch 313/500
1253/1253 - 0s - loss: 3.2556e-04
Epoch 314/500
1253/1253 - 0s - loss: 4.2009e-04
Epoch 315/500
1253/1253 - 0s - loss: 5.8796e-04
Epoch 316/500
1253/1253 - 0s - loss: 8.6407e-04
Epoch 317/500
1253/1253 - 0s - loss: 0.0013
Epoch 318/500
1253/1253 - 0s - loss: 0.0018
Epoch 319/500
1253/1253 - 0s - loss: 0.0021
Epoch 320/500
1253/1253 - 0s - loss: 0.0020
Epoch 321/500
1253/1253 - 0s - loss: 0.0013
Epoch 322/500
1253/1253 - 0s - loss: 7.3372e-04
Epoch 323/500
1253/1253 - 0s - loss: 4.0706e-04
Epoch 324/500
1253/1253 - 0s - loss: 3.0345e-04
Epoch 325/500
1253/1253 - 0s - loss: 3.0271e-04
Epoch 326/500
1253/1253 - 0s - loss: 3.3675e-04
Epoch 327/500
1253/1253 - 0s - loss: 3.7171e-04
Epoch 328/500
1253/1253 - 0s - loss: 3.8818e-04
Epoch 329/500
1253/1253 - 0s - loss: 3.7861e-04
Epoch 330/500
1253/1253 - 0s - loss: 3.4829e-04
Epoch 331/500
1253/1253 - 0s - loss: 3.0824e-04
Epoch 332/500
1253/1253 - 0s - loss: 2.7430e-04
Epoch 333/500
1253/1253 - 0s - loss: 2.5015e-04
Epoch 334/500
1253/1253 - 0s - loss: 2.3696e-04
Epoch 335/500
1253/1253 - 0s - loss: 2.3395e-04
Epoch 336/500
1253/1253 - 0s - loss: 2.4129e-04
Epoch 337/500
1253/1253 - 0s - loss: 2.5914e-04
Epoch 338/500
1253/1253 - 0s - loss: 2.8800e-04
Epoch 339/500
1253/1253 - 0s - loss: 3.3140e-04
Epoch 340/500
1253/1253 - 0s - loss: 3.9460e-04
Epoch 341/500
1253/1253 - 0s - loss: 4.7995e-04
Epoch 342/500
1253/1253 - 0s - loss: 5.9431e-04
Epoch 343/500
1253/1253 - 0s - loss: 7.4143e-04
Epoch 344/500
1253/1253 - 0s - loss: 9.1190e-04
Epoch 345/500
1253/1253 - 0s - loss: 0.0011
Epoch 346/500
1253/1253 - 0s - loss: 0.0011
Epoch 347/500
1253/1253 - 0s - loss: 0.0011
Epoch 348/500
1253/1253 - 0s - loss: 9.0563e-04
Epoch 349/500
1253/1253 - 0s - loss: 6.8273e-04
Epoch 350/500
1253/1253 - 0s - loss: 4.9073e-04
Epoch 351/500
1253/1253 - 0s - loss: 3.6478e-04
Epoch 352/500

1253/1253 - 0s - loss: 3.0023e-04
Epoch 353/500
1253/1253 - 0s - loss: 2.8095e-04
Epoch 354/500
1253/1253 - 0s - loss: 2.9117e-04
Epoch 355/500
1253/1253 - 0s - loss: 3.2000e-04
Epoch 356/500
1253/1253 - 0s - loss: 3.5843e-04
Epoch 357/500
1253/1253 - 0s - loss: 3.9511e-04
Epoch 358/500
1253/1253 - 0s - loss: 4.2355e-04
Epoch 359/500
1253/1253 - 0s - loss: 4.3393e-04
Epoch 360/500
1253/1253 - 0s - loss: 4.3255e-04
Epoch 361/500
1253/1253 - 0s - loss: 4.2099e-04
Epoch 362/500
1253/1253 - 0s - loss: 3.9675e-04
Epoch 363/500
1253/1253 - 0s - loss: 3.6207e-04
Epoch 364/500
1253/1253 - 0s - loss: 3.2325e-04
Epoch 365/500
1253/1253 - 0s - loss: 2.8622e-04
Epoch 366/500
1253/1253 - 0s - loss: 2.5835e-04
Epoch 367/500
1253/1253 - 0s - loss: 2.4332e-04
Epoch 368/500
1253/1253 - 0s - loss: 2.4152e-04
Epoch 369/500
1253/1253 - 0s - loss: 2.6595e-04
Epoch 370/500
1253/1253 - 0s - loss: 3.2714e-04
Epoch 371/500
1253/1253 - 0s - loss: 4.4917e-04
Epoch 372/500
1253/1253 - 0s - loss: 6.7527e-04
Epoch 373/500
1253/1253 - 0s - loss: 0.0011
Epoch 374/500
1253/1253 - 0s - loss: 0.0016
Epoch 375/500
1253/1253 - 0s - loss: 0.0022
Epoch 376/500
1253/1253 - 0s - loss: 0.0023
Epoch 377/500
1253/1253 - 0s - loss: 0.0016
Epoch 378/500
1253/1253 - 0s - loss: 8.2216e-04
Epoch 379/500
1253/1253 - 0s - loss: 4.1409e-04
Epoch 380/500
1253/1253 - 0s - loss: 3.0847e-04
Epoch 381/500
1253/1253 - 0s - loss: 3.2455e-04
Epoch 382/500
1253/1253 - 0s - loss: 3.6783e-04
Epoch 383/500
1253/1253 - 0s - loss: 3.9754e-04
Epoch 384/500
1253/1253 - 0s - loss: 3.9436e-04
Epoch 385/500
1253/1253 - 0s - loss: 3.6521e-04
Epoch 386/500
1253/1253 - 0s - loss: 3.2024e-04
Epoch 387/500
1253/1253 - 0s - loss: 2.7974e-04
Epoch 388/500
1253/1253 - 0s - loss: 2.5078e-04
Epoch 389/500
1253/1253 - 0s - loss: 2.3516e-04
Epoch 390/500
1253/1253 - 0s - loss: 2.3320e-04
Epoch 391/500
1253/1253 - 0s - loss: 2.4374e-04
Epoch 392/500
1253/1253 - 0s - loss: 2.6592e-04
Epoch 393/500
1253/1253 - 0s - loss: 2.9850e-04
Epoch 394/500
1253/1253 - 0s - loss: 3.4259e-04
Epoch 395/500
1253/1253 - 0s - loss: 4.0121e-04
Epoch 396/500
1253/1253 - 0s - loss: 4.7391e-04
Epoch 397/500
1253/1253 - 0s - loss: 5.5917e-04
Epoch 398/500
1253/1253 - 0s - loss: 6.5350e-04
Epoch 399/500
1253/1253 - 0s - loss: 7.4197e-04
Epoch 400/500
1253/1253 - 0s - loss: 8.0561e-04
Epoch 401/500
1253/1253 - 0s - loss: 8.1954e-04
Epoch 402/500
1253/1253 - 0s - loss: 7.7398e-04
Epoch 403/500
1253/1253 - 0s - loss: 6.8028e-04
Epoch 404/500
1253/1253 - 0s - loss: 5.6265e-04
Epoch 405/500
1253/1253 - 0s - loss: 4.5092e-04
Epoch 406/500
1253/1253 - 0s - loss: 3.6366e-04
Epoch 407/500
1253/1253 - 0s - loss: 3.0578e-04
Epoch 408/500
1253/1253 - 0s - loss: 2.7406e-04
Epoch 409/500
1253/1253 - 0s - loss: 2.6443e-04
Epoch 410/500
1253/1253 - 0s - loss: 2.7158e-04
Epoch 411/500
1253/1253 - 0s - loss: 2.9117e-04
Epoch 412/500
1253/1253 - 0s - loss: 3.1891e-04
Epoch 413/500
1253/1253 - 0s - loss: 3.5223e-04
Epoch 414/500
1253/1253 - 0s - loss: 3.8965e-04
Epoch 415/500
1253/1253 - 0s - loss: 4.2424e-04
Epoch 416/500
1253/1253 - 0s - loss: 4.4840e-04
Epoch 417/500
1253/1253 - 0s - loss: 4.6394e-04
Epoch 418/500
1253/1253 - 0s - loss: 4.6843e-04
Epoch 419/500
1253/1253 - 0s - loss: 4.5333e-04
Epoch 420/500
1253/1253 - 0s - loss: 4.1774e-04
Epoch 421/500
1253/1253 - 0s - loss: 3.7111e-04
Epoch 422/500
1253/1253 - 0s - loss: 3.2149e-04
Epoch 423/500
1253/1253 - 0s - loss: 2.7982e-04
Epoch 424/500
1253/1253 - 0s - loss: 2.5121e-04
Epoch 425/500
1253/1253 - 0s - loss: 2.4602e-04
Epoch 426/500
1253/1253 - 0s - loss: 2.8085e-04
Epoch 427/500
1253/1253 - 0s - loss: 3.7716e-04
Epoch 428/500
1253/1253 - 0s - loss: 5.8216e-04
Epoch 429/500
1253/1253 - 0s - loss: 9.6511e-04
Epoch 430/500
1253/1253 - 0s - loss: 0.0016
Epoch 431/500
1253/1253 - 0s - loss: 0.0023
Epoch 432/500
1253/1253 - 0s - loss: 0.0025
Epoch 433/500
1253/1253 - 0s - loss: 0.0018
Epoch 434/500
1253/1253 - 0s - loss: 8.8009e-04
Epoch 435/500
1253/1253 - 0s - loss: 4.1377e-04
Epoch 436/500
1253/1253 - 0s - loss: 2.9828e-04
Epoch 437/500
1253/1253 - 0s - loss: 3.0994e-04
Epoch 438/500
1253/1253 - 0s - loss: 3.4523e-04
Epoch 439/500
1253/1253 - 0s - loss: 3.6626e-04
Epoch 440/500
1253/1253 - 0s - loss: 3.6221e-04
Epoch 441/500
1253/1253 - 0s - loss: 3.3815e-04
Epoch 442/500
1253/1253 - 0s - loss: 3.0220e-04
Epoch 443/500
1253/1253 - 0s - loss: 2.6752e-04
Epoch 444/500
1253/1253 - 0s - loss: 2.4372e-04
Epoch 445/500
1253/1253 - 0s - loss: 2.3259e-04
Epoch 446/500
1253/1253 - 0s - loss: 2.3231e-04
Epoch 447/500
1253/1253 - 0s - loss: 2.4193e-04
Epoch 448/500
1253/1253 - 0s - loss: 2.6021e-04
Epoch 449/500
1253/1253 - 0s - loss: 2.8631e-04
Epoch 450/500
1253/1253 - 0s - loss: 3.2050e-04
Epoch 451/500
1253/1253 - 0s - loss: 3.6321e-04
Epoch 452/500
1253/1253 - 0s - loss: 4.1497e-04
Epoch 453/500
1253/1253 - 0s - loss: 4.7451e-04
Epoch 454/500
1253/1253 - 0s - loss: 5.3859e-04
Epoch 455/500
1253/1253 - 0s - loss: 5.9962e-04
Epoch 456/500
1253/1253 - 0s - loss: 6.4782e-04
Epoch 457/500
1253/1253 - 0s - loss: 6.7601e-04
Epoch 458/500
1253/1253 - 0s - loss: 6.7445e-04
Epoch 459/500
1253/1253 - 0s - loss: 6.3861e-04
Epoch 460/500
1253/1253 - 0s - loss: 5.7383e-04
Epoch 461/500
1253/1253 - 0s - loss: 4.9316e-04
Epoch 462/500
1253/1253 - 0s - loss: 4.1571e-04
Epoch 463/500
1253/1253 - 0s - loss: 3.5087e-04
Epoch 464/500
1253/1253 - 0s - loss: 3.0310e-04
Epoch 465/500
1253/1253 - 0s - loss: 2.7268e-04
Epoch 466/500
1253/1253 - 0s - loss: 2.5754e-04
Epoch 467/500
1253/1253 - 0s - loss: 2.5594e-04
Epoch 468/500
1253/1253 - 0s - loss: 2.6564e-04
Epoch 469/500
1253/1253 - 0s - loss: 2.8630e-04
Epoch 470/500
1253/1253 - 0s - loss: 3.1794e-04
Epoch 471/500
1253/1253 - 0s - loss: 3.6054e-04
Epoch 472/500
1253/1253 - 0s - loss: 4.1146e-04
Epoch 473/500
1253/1253 - 0s - loss: 4.6122e-04
Epoch 474/500
1253/1253 - 0s - loss: 5.0999e-04
Epoch 475/500
1253/1253 - 0s - loss: 5.3767e-04
Epoch 476/500
1253/1253 - 0s - loss: 5.4096e-04
Epoch 477/500
1253/1253 - 0s - loss: 5.0332e-04
Epoch 478/500
1253/1253 - 0s - loss: 4.6462e-04
Epoch 479/500
1253/1253 - 0s - loss: 4.1051e-04
Epoch 480/500
1253/1253 - 0s - loss: 3.5424e-04
Epoch 481/500
1253/1253 - 0s - loss: 3.0488e-04
Epoch 482/500
1253/1253 - 0s - loss: 2.6720e-04
Epoch 483/500
1253/1253 - 0s - loss: 2.4963e-04
Epoch 484/500
1253/1253 - 0s - loss: 2.6448e-04
Epoch 485/500
1253/1253 - 0s - loss: 3.2918e-04
Epoch 486/500
1253/1253 - 0s - loss: 4.6357e-04
Epoch 487/500
1253/1253 - 0s - loss: 7.1292e-04
Epoch 488/500
1253/1253 - 0s - loss: 0.0011
Epoch 489/500
1253/1253 - 0s - loss: 0.0016
Epoch 490/500
1253/1253 - 0s - loss: 0.0020
Epoch 491/500
1253/1253 - 0s - loss: 0.0018
Epoch 492/500
1253/1253 - 0s - loss: 0.0012
Epoch 493/500
1253/1253 - 0s - loss: 6.0205e-04
Epoch 494/500
1253/1253 - 0s - loss: 3.4786e-04
Epoch 495/500
1253/1253 - 0s - loss: 2.9174e-04
Epoch 496/500
1253/1253 - 0s - loss: 3.1269e-04
Epoch 497/500
1253/1253 - 0s - loss: 3.4682e-04
Epoch 498/500
1253/1253 - 0s - loss: 3.6495e-04
Epoch 499/500
1253/1253 - 0s - loss: 3.5636e-04
Epoch 500/500
1253/1253 - 0s - loss: 3.2679e-04

In [8]:

model=load_model('gold.h5') 
trainPredict = model.predict(X)
testPredict = scaler.inverse_transform(trainPredict)
testY = scaler.inverse_transform(y)
df_GOLD['GOLD_T']=pd.DataFrame(testPredict[:,0],columns=['GOLD_T'])
df_GOLD.dropna(inplace=True)
df_GOLD

         Date  USD (PM)       GOLD_T
0     9/12/16   1324.60  1307.016968
1     9/13/16   1323.65  1306.083618
2     9/14/16   1321.75  1304.243774
3     9/15/16   1310.80  1293.732056
4     9/16/16   1308.35  1291.379150
...       ...       ...          ...
1248  8/18/21   1783.45  1803.662964
1249  8/19/21   1782.05  1814.476562
1250  8/20/21   1779.05  1812.435303
1251  8/23/21   1802.00  1793.629639
1252  8/24/21   1808.45  1777.718506

[1243 rows x 3 columns]

In [13]:
df_predict = pd.merge(df_BM, df_GOLD, how='outer', on='Date')
df_predict["Date"] = df_predict["Date"].apply(lambda x: time.strftime('%Y/%m/%d', time.strptime(x, '%m/%d/%y')))
df_predict = df_predict.sort_values("Date")

df = pd.merge(df_origin, df_predict, how='left', on='Date')
df[1800:]

,Date,bitcoin,gold,gold_future,Value,Bit_T,USD (PM),GOLD_T
1800,2021/08/16,47056.41,1786.35,1786.35,47056.41,48138.953125,1786.35,1805.888794
1801,2021/08/17,45982.55,1789.45,1789.45,45982.55,47061.171875,1789.45,1802.937744
1802,2021/08/18,44648.57,1783.45,1783.45,44648.57,45725.988281,1783.45,1803.662964
1803,2021/08/19,44777.86,1782.05,1782.05,44777.86,45855.218750,1782.05,1814.476562
1804,2021/08/20,46734.65,1779.05,1779.05,46734.65,47815.738281,1779.05,1812.435303
1805,2021/08/21,49327.75,NaN,1802.00,49327.75,50427.375000,NaN,NaN
1806,2021/08/22,48932.02,NaN,1802.00,48932.02,50027.796875,NaN,NaN
1807,2021/08/23,49335.68,1802.00,1802.00,49335.68,50435.386719,1802.00,1793.629639
1808,2021/08/24,49523.50,1808.45,1808.45,49523.50,50625.160156,1808.45,1777.718506
1809,2021/08/25,47744.58,1788.70,1788.70,47744.58,48831.027344,NaN,NaN
1810,2021/08/26,48972.09,1786.60,1786.60,48972.09,50068.242188,NaN,NaN
1811,2021/08/27,46962.80,1798.50,1798.50,46962.80,48044.894531,NaN,NaN
1812,2021/08/28,49056.86,NaN,1814.85,49056.86,50153.816406,NaN,NaN
1813,2021/08/29,48897.65,NaN,1814.85,48897.65,49993.113281,NaN,NaN
1814,2021/08/30,48806.78,NaN,1814.85,48806.78,49901.421875,NaN,NaN
1815,2021/08/31,47074.77,1814.85,1814.85,47074.77,48157.406250,NaN,NaN
1816,2021/09/01,47155.87,1811.80,1811.80,47155.87,48238.910156,NaN,NaN
1817,2021/09/02,48862.76,1812.55,1812.55,48862.76,49957.906250,NaN,NaN
1818,2021/09/03,49329.01,1823.70,1823.70,49329.01,50428.648438,NaN,NaN
1819,2021/09/04,50035.33,NaN,1821.60,50035.33,51142.750000,NaN,NaN
1820,2021/09/05,49947.38,NaN,1821.60,49947.38,51053.761719,NaN,NaN
1821,2021/09/06,51769.06,1821.60,1821.60,51769.06,52900.636719,NaN,NaN
1822,2021/09/07,52677.40,1802.15,1802.15,52677.40,53824.527344,NaN,NaN
1823,2021/09/08,46809.17,1786.00,1786.00,46809.17,47890.578125,NaN,NaN
1824,2021/09/09,46078.38,1788.25,1788.25,NaN,NaN,NaN,NaN
1825,2021/09/10,46368.69,1794.60,1794.60,NaN,NaN,NaN,NaN

In [101]:
from sko.operators import ranking, selection, crossover, mutation
from sko.GA import GA

In [115]:
def sign(m):
    return m/abs(m+1e7)
def model_1_ga(z1,z2,m1,m2,n1,n2,us):
    demo_func = demo_func = lambda x: -((n1 / m1) * (z1 + x[0]) + (n2 / m2) * (z2 + x[1])+(us-(x[0]*(1+sign(x[0])*0.04)+x[1]*(1+sign(x[1])*0.08))))

    constraint_ueq = [lambda x: x[0]*(1+sign(x[0])*0.04)+x[1]*(1+sign(x[1])*0.08) - us,
        lambda x: (-z1 - z2) - (x[0] + x[1]),
        lambda x: 0.04  - ((n1 / m1) - 1)* sign(x[0]),
        lambda x: 0.08 - ((n2 / m2) - 1)* sign(x[1]),
        
            ]

    ga = GA(func=demo_func, n_dim=2, size_pop=100, max_iter=500, prob_mut=0.001,
            lb=[-z1, -z2], 
            ub=[us/1.04, us/1.08], 
            precision=[1e-7, 1e-7], 
            constraint_ueq=constraint_ueq)

    ga.register(operator_name='selection', operator=selection.selection_roulette_2)
    ga.register(operator_name='ranking', operator=ranking.ranking)
    ga.register(operator_name='crossover', operator=crossover.crossover_2point_bit)
    ga.register(operator_name='mutation', operator=mutation.mutation)
    best, func = ga.run()
    
    return -func[0],best[0],best[1],(us-(best[0]*(1+sign(best[0])*0.04)+best[1]*(1+sign(best[1])*0.08)))

In [116]:
def model_2_ga(z1,z2,m2,n2,us):

    demo_func = lambda x: -(z1 + (n2 / m2) * (z2 + x[0])+(us-x[0]*(1+sign(x[0])*0.08)))


    constraint_ueq = [
        lambda x: x[0]*(1+sign(x[0])*0.08) - us,
        lambda x: - z2 - x[0],
        lambda x: 0.08  - ((n2 / m2) - 1)*sign(x[0])
    ]
    ga = GA(func=demo_func, n_dim=1, size_pop=100, max_iter=500, prob_mut=0.001,
            lb=[-z2], ub=[us/1.08], precision=[1e-7], constraint_ueq=constraint_ueq)

    ga.register(operator_name='selection', operator=selection.selection_roulette_2)
    ga.register(operator_name='ranking', operator=ranking.ranking)
    ga.register(operator_name='crossover', operator=crossover.crossover_2point_bit) 
    ga.register(operator_name='mutation', operator=mutation.mutation)
    best, func = ga.run()
    return -func[0],best[0],(us-best[0]*(1+sign(best[0])*0.08))

In [117]:
# 黄金持有
us=1000
z1 = 0
z2 = 0
alldata=[]
for i in range(df.shape[0]):
    try:
        if i== df.shape[0]-15:
            break
        # m1 真实的今日黄金价格
        m1=df['gold'].iloc[i]
       
        # m2 真实的今日比特币价格
        m2=df['bitcoin'].iloc[i]
        
        n1= df['GOLD_T'].iloc[i+1]
        # n2 预测的明日比特币价格
        n2= df['Bit_T'].iloc[i+1]
         # n1 真实的明日黄金价格
        N1= df['gold_future'].iloc[i+1]
        # n2 真实的明日比特币价格
        N2= df['bitcoin'].iloc[i+1]
        if (np.isnan(m1)==True) or (np.isnan(n1)==True):
            _,x_2,us=model_2_ga(z1,z2,m2,n2,us)
            z2=N2 / m2 * (z2 + x_2)
            alldata.append([df['Date'].iloc[i],m1,m2,n1,n2,N1,N2,z1,z2,0,x_2,us,z1+z2+us])
        else:
            _,x_1,x_2,us=model_1_ga(z1,z2,m1,m2,n1,n2,us)
            z1=N1 / m1 * (z1 + x_1) 
            z2=N2 / m2 * (z2 + x_2)
            alldata.append([df['Date'].iloc[i],m1,m2,n1,n2,N1,N2,z1,z2,x_1,x_2,us,z1+z2+us])
        if i%100==0:
            print(z1+z2+us)
    except:
        print(df['Date'].iloc[i])
        break

982.1493976471926
1327.7474867468345
1666.8954207816716
4085.7007685815033
9027.084859113873
34650.45927876552
41287.86104631353
26731.38187226461
18918.53610581379
16215.083964518382
33402.72401145938
57452.18444673821
40254.542456681
61342.10995090361
84582.96109093013
108508.81142413216
492196.3756902294
1371279.7239005833
2854493.3702504546

In [118]:

cs1=['transaction date','real gold price today','real bitcoin price today','Predicted gold price for tomorrow','Predicted Bitcoin price for tomorrow', 'The real gold price of tomorrow','The real bitcoin price of tomorrow','Gold holdings today','Today Bitcoin holdings','Today gold trading volume','Today bitcoin transaction volume','Today dollar holding','Total assets of the next trading day']
alldata=pd.DataFrame(alldata,columns=cs1)
alldata

,transaction date,real gold price today,real bitcoin price today,Predicted gold price for tomorrow,Predicted Bitcoin price for tomorrow,The real gold price of tomorrow,The real bitcoin price of tomorrow,Gold holdings today,Today Bitcoin holdings,Today gold trading volume,Today bitcoin transaction volume,Today dollar holding,Total assets of the next trading day
0,2016/09/11,NaN,621.65,1307.016968,792.848755,1324.60,609.67,0.000000,9.080798e+02,0.000000,9.259235e+02,7.406963e+01,9.821494e+02
1,2016/09/12,1324.60,609.67,1306.083618,793.668823,1323.65,610.92,0.073291,9.786271e+02,0.073344,6.854501e+01,5.451244e+00,9.841517e+02
2,2016/09/13,1323.65,610.92,1304.243774,792.291382,1321.75,608.82,0.029966,9.802929e+02,-0.043282,5.047120e+00,4.474060e-01,9.807703e+02
3,2016/09/14,1321.75,608.82,1293.732056,793.314575,1310.80,610.38,0.010170,9.832173e+02,-0.019712,4.115036e-01,5.561415e-02,9.832831e+02
4,2016/09/15,1310.80,610.38,1291.379150,792.481445,1308.35,609.11,0.000784,9.812050e+02,-0.009384,3.351087e-02,3.148746e-02,9.812373e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1806,2021/08/22,NaN,48932.02,1793.629639,50435.386719,1802.00,49335.68,96001.629007,2.965494e+06,0.000000,3.497704e+00,3.144534e-01,3.061496e+06
1807,2021/08/23,1802.00,49335.68,1777.718506,50625.160156,1808.45,49523.50,1165.304140,2.976447e+06,-94840.481030,-3.359712e+02,9.514044e+04,3.072752e+06
1808,2021/08/24,1808.45,49523.50,NaN,48831.027344,1788.70,47744.58,1165.304140,2.115711e+06,0.000000,-7.819058e+05,8.717403e+05,2.988617e+06
1809,2021/08/25,1788.70,47744.58,NaN,50068.242188,1786.60,48972.09,1165.304140,2.998024e+06,0.000000,8.071658e+05,5.975169e+04,3.058941e+06
1810,2021/08/26,1786.60,48972.09,NaN,48044.894531,1798.50,46962.80,1165.304140,1.898517e+06,0.000000,-1.018279e+06,1.068796e+06,2.968478e+06

In [119]:
alldata.to_excel('alpha4.xlsx',index=None)